---
title: "Reproducible Research: Peer Assessment 1"
output: 
  html_document:
    keep_md: true
---


## Loading and preprocessing the data
```{r, message=FALSE}
knitr::opts_chunk$set(cache=TRUE, echo=TRUE) # Setting global options
library(dplyr)
library(lubridate)
library(stringr)
library("lattice")

myDat <- read.csv("activity.csv")
myDat <- myDat[complete.cases(myDat),] # Removing incomplete cases
myDat$date <- as.factor(myDat$date) # Setting the Date in the dataset as a factor

# adding a column with a proper date-time stamp and another columns with just the time
myDat$origInterval <- myDat$interval
myDat$interval <- str_pad(myDat$interval, 4, pad = "0")
myDat$time <- parse_date_time(paste(myDat$interval, "00", sep = ""), "%H%M%S")

myDat$dateTime <- paste(myDat$date, myDat$interval, sep = ":")
myDat$dateTime <- parse_date_time(myDat$dateTime, "%y%m%d:%H%M")

byDayGrouping <- group_by(myDat, date)
byIntervalGrouping <- group_by(myDat, origInterval)

totalSteps <- sum(myDat$steps)
totalStepsAvg <- mean(myDat$steps)
```


## What is mean total number of steps taken per day?
```{r}
totalStepsByDay <- summarise(byDayGrouping, totalSteps=sum(steps))
hist(totalStepsByDay$totalSteps)

stepsByDayTotalAvg <- mean(totalStepsByDay$totalSteps)
print(paste("Mean total number of steps taken per day:", as.character(stepsByDayTotalAvg)))

totalStepsMedian <- median(totalStepsByDay$totalSteps)
print(paste("Median number of steps taken per day:", as.character(totalStepsMedian)))

```


## What is the average daily activity pattern?
```{r, fig.width=10}
t1 <- summarise(byIntervalGrouping, stepsAvg=mean(steps))
xyplot(stepsAvg ~ origInterval, data = t1, type = "l", scales=list(x=list(rot=45)))

maxSteps <- max(byDayGrouping[byDayGrouping$steps > 0,]$steps)
intervalWithMax <- byDayGrouping[byDayGrouping$steps == maxSteps,]$interval
print(paste("Interval(s): ", intervalWithMax, ", Had the greates number of steps of: ", maxSteps, sep = ""))
```


## Imputing missing values



## Are there differences in activity patterns between weekdays and weekends?
